<Project Sdk="Aspire.AppHost.Sdk/13.4.2">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d341f139-def8-4f87-b1a2-cad171a9e1fa</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AspireNextjsKeycloak.ApiService\AspireNextjsKeycloak.ApiService.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.4.2-preview.1.26303.6" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.2" />
  </ItemGroup>
</Project>
